dist: trusty
sudo: false
language: python
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
install:
  - wget -q https://data.qiime2.org/distro/core/qiime2-2019.1-py36-linux-conda.yml
  - wget -q https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.0.1/sirius-4.0.1-linux64-headless.zip
  - unzip sirius-4.0.1-linux64-headless.zip
  - mv sirius-linux64-headless-4.0.1 q2_qemistree/tests/data/
  - conda env create -q -n test-env --file qiime2-2019.1-py36-linux-conda.yml
  - source activate test-env
  - conda install -q pytest-cov
  - pip install -q flake8 coveralls
  - make install
script:
  - make lint
  - make test-cov
after_success:
  - coveralls
